### ISSUE TITLE
Installation failed because of gpg: keyblock resource limit

### ISSUE THREAD

**Issue by alevis** [tiliado/tiliado-repositories#10]
- ['/usr/bin/tiliado-repositories', '-d', 'ubuntu', '-r', 'trusty', '-v', 'stable', '-p', 'nuvolaplayer', '-i', 'nuvolaplayer3', '--server', 'tiliado.eu', '--protocol', 'https']
- ['apt-get', 'remove', '-y', 'nuvolaplayer3*']
  Reading package lists...
  Building dependency tree...
  Reading state information...
  The following packages were automatically installed and are no longer required:
  braindump calligraauthor calligraflow calligraflow-data calligraplan
  calligrasheets calligrastage calligrastage-data calligrawords
  calligrawords-common calligrawords-data karbon kdepim-runtime
  kdepimlibs-kio-plugins kexi krita krita-data libaccounts-qt1
  libakonadi-calendar4 libakonadi-contact4 libakonadi-kabc4 libakonadi-kcal4
  libakonadi-kmime4 libakonadi-notes4 libakonadi-socialutils4 libcrypto++9
  libcurl3-gnutls:i386 libdmtx0a libkalarmcal2 libkcal4 libkcalutils4
  libkdcraw-data libkdcraw23 libkfbapi1 libkgapi2-2 libkholidays4 libkimap4
  libkmbox4 libkmime4 libkolab0 libkolabxml1 libkpimidentities4
  libkpimtextedit4 libkpimutils4 libmailtransport4 libmicroblog4
  libodfgen-0.0-0 libprison0 libqrencode3 librtmp0:i386 libsignon-qt1
  libxerces-c3.1 nspluginviewer:i386 nspluginwrapper
  nuvolaplayer-flashplugin-multiarch:i386 tsocks
  Use 'apt-get autoremove' to remove them.
  The following packages will be REMOVED:
  nuvolaplayer nuvolaplayer-flashplugin
  0 upgraded, 0 newly installed, 2 to remove and 38 not upgraded.
  After this operation, 2,151 kB disk space will be freed.
  (Reading database ... 936776 files and directories currently installed.)
  Removing nuvolaplayer (2.5-0.1~trusty) ...
  Removing nuvolaplayer-flashplugin (0.7-0fenryxo1~trusty1) ...
  [INFO] Uninstalling wrapped Flash plugin from '/opt/nuvolaplayer'.
  [INFO] Done.
  Processing triggers for hicolor-icon-theme (0.13-1) ...
  Processing triggers for mime-support (3.54ubuntu1.1) ...
  Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
  Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
  Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
  Rebuilding /usr/share/applications/bamf-2.index...
  Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
- ['apt-key', 'adv', '--keyserver', 'hkp://keyserver.ubuntu.com:80', '--recv-keys', '40554B8FA5FE6F6A']
  Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.Uuy27iyKI6 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/apt.postgresql.org.gpg --keyring /etc/apt/trusted.gpg.d/atareao-atareao.gpg --keyring /etc/apt/trusted.gpg.d/caffeine-developers-ppa.gpg --keyring /etc/apt/trusted.gpg.d/captiva-ppa.gpg --keyring /etc/apt/trusted.gpg.d/chris-lea-node_js.gpg --keyring /etc/apt/trusted.gpg.d/costales-anoise.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyring /etc/apt/trusted.gpg.d/fontforge-fontforge.gpg --keyring /etc/apt/trusted.gpg.d/kilian-f_lux.gpg --keyring /etc/apt/trusted.gpg.d/libreoffice-ppa.gpg --keyring /etc/apt/trusted.gpg.d/mc3man-trusty-media.gpg --keyring /etc/apt/trusted.gpg.d/moka-stable.gpg --keyring /etc/apt/trusted.gpg.d/mystic-mirage-komodo-edit.gpg --keyring /etc/apt/trusted.gpg.d/n-muench-burg.gpg --keyring /etc/apt/trusted.gpg.d/nilarimogard-webupd8.gpg --keyring /etc/apt/trusted.gpg.d/no1wantdthisname-openjdk-fontfix.gpg --keyring /etc/apt/trusted.gpg.d/noobslab-icons.gpg --keyring /etc/apt/trusted.gpg.d/noobslab-noobslab-conky.gpg --keyring /etc/apt/trusted.gpg.d/noobslab-themes.gpg --keyring /etc/apt/trusted.gpg.d/notepadqq-team-notepadqq.gpg --keyring /etc/apt/trusted.gpg.d/numix-ppa.gpg --keyring /etc/apt/trusted.gpg.d/nuvola-player-builders-stable.gpg --keyring /etc/apt/trusted.gpg.d/oibaf-graphics-drivers.gpg --keyring /etc/apt/trusted.gpg.d/pipelight-stable.gpg --keyring /etc/apt/trusted.gpg.d/pithos-ppa.gpg --keyring /etc/apt/trusted.gpg.d/snwh-pulp.gpg --keyring /etc/apt/trusted.gpg.d/steam.gpg --keyring /etc/apt/trusted.gpg.d/team-xbmc-ppa.gpg --keyring /etc/apt/trusted.gpg.d/teejee2008-ppa.gpg --keyring /etc/apt/trusted.gpg.d/tiheum-equinox.gpg --keyring /etc/apt/trusted.gpg.d/ubuntu-desktop-ubuntu-make.gpg --keyring /etc/apt/trusted.gpg.d/ubuntu-mozilla-daily-firefox-aurora.gpg --keyring /etc/apt/trusted.gpg.d/ubuntu-sdk-team-ppa.gpg --keyring /etc/apt/trusted.gpg.d/ubuntu-toolchain-r-test.gpg --keyring /etc/apt/trusted.gpg.d/ubuntuhandbook1-sigil.gpg --keyring /etc/apt/trusted.gpg.d/upubuntu-com-office.gpg --keyring /etc/apt/trusted.gpg.d/webupd8team-atom.gpg --keyring /etc/apt/trusted.gpg.d/webupd8team-brackets.gpg --keyring /etc/apt/trusted.gpg.d/webupd8team-java.gpg --keyring /etc/apt/trusted.gpg.d/webupd8team-sublime-text-3.gpg --keyring /etc/apt/trusted.gpg.d/webupd8team-y-ppa-manager.gpg --keyring /etc/apt/trusted.gpg.d/wfg-0ad.gpg --keyring /etc/apt/trusted.gpg.d/wiznote-team-ppa.gpg --keyring /etc/apt/trusted.gpg.d/xorg-edgers-ppa.gpg --keyring /etc/apt/trusted.gpg.d/yannubuntu-boot-repair.gpg --keyring /etc/apt/trusted.gpg.d/yorba-daily-builds.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 40554B8FA5FE6F6A
  gpg: keyblock resource `/etc/apt/trusted.gpg.d/upubuntu-com-office.gpg': resource limit
  gpg: keyblock resource`/etc/apt/trusted.gpg.d/webupd8team-atom.gpg': resource limit
  gpg: keyblock resource `/etc/apt/trusted.gpg.d/webupd8team-brackets.gpg': resource limit
  gpg: keyblock resource`/etc/apt/trusted.gpg.d/webupd8team-java.gpg': resource limit
  gpg: keyblock resource `/etc/apt/trusted.gpg.d/webupd8team-sublime-text-3.gpg': resource limit
  gpg: keyblock resource`/etc/apt/trusted.gpg.d/webupd8team-y-ppa-manager.gpg': resource limit
  gpg: keyblock resource `/etc/apt/trusted.gpg.d/wfg-0ad.gpg': resource limit
  gpg: keyblock resource`/etc/apt/trusted.gpg.d/wiznote-team-ppa.gpg': resource limit
  gpg: keyblock resource `/etc/apt/trusted.gpg.d/xorg-edgers-ppa.gpg': resource limit
  gpg: keyblock resource`/etc/apt/trusted.gpg.d/yannubuntu-boot-repair.gpg': resource limit
  gpg: keyblock resource `/etc/apt/trusted.gpg.d/yorba-daily-builds.gpg': resource limit
  gpg: requesting key A5FE6F6A from hkp server keyserver.ubuntu.com
  gpg: key A5FE6F6A: public key "Ji\xc5\x99\udced Janou\xc5\xa1ek janousek.jiri@gmail.com" imported
  gpg: Total number processed: 1
  gpg:               imported: 1  (RSA: 1)
  Subprocess Error: Command '['apt-key', 'adv', '--keyserver', 'hkp://keyserver.ubuntu.com:80', '--recv-keys', '40554B8FA5FE6F6A']' returned non-zero exit status 2
- [Return code = 4]

**Comment by jiri-janousek** [comment]
Hello @alevis. Thanks for taking the time to report this issue. The Tiliado Repository Installer contains a lot of tweaks to work around broken apt source lists and apt cache of users' systems. However, this issue is new. Could you follow this procedure to clean up apt gpg keyrings? [Fix gpg resource limits and missing keys](https://medium.com/@foxoman/ubuntu-tip-fix-gpg-resource-limits-and-missing-keys-ec7f1da4c02)
