### ISSUE TITLE
nuvolaplayer installation failure

### ISSUE THREAD

**Issue by davehyde73** [tiliado/tiliado-repositories#11]
E: Some index files failed to download. They have been ignored, or old ones used instead.

Warning: Database update command failed, probably because of broken repositories in your APT sources lists. Error code:
- ['apt-get', 'install', '-y', 'nuvolaplayer3']
  Reading package lists...
  Building dependency tree...
  Reading state information...
  W: Duplicate sources.list entry http://dl.bintray.com/kusti8/chromium-rpi/ jessie/main armhf Packages (/var/lib/apt/lists/dl.bintray.com_kusti8_chromium-rpi_dists_jessie_main_binary-armhf_Packages)
  W: You may want to run apt-get update to correct these problems
  E: Unable to locate package nuvolaplayer3
  Subprocess Error: Command '['apt-get', 'install', '-y', 'nuvolaplayer3']' returned non-zero exit status 100
- [Return code = 4]

**Comment by jiri-janousek** [comment]
Hello @davehyde73. It seem you are running the armhf architecture. However, Nuvola Player provides packages only for i386 and amd64. The installer should show this information but it hasn't been implemented yet (#8). I'm sorry for the confusion.
