### ISSUE TITLE
installing tiliado repositories failed

### ISSUE THREAD

**Issue by illumine666** [tiliado/tiliado-repositories#14]
+ ['/usr/bin/tiliado-repositories', '-d', 'ubuntu', '-r', 'xenial', '-v', 'stable', '-p', 'diorite', '-i', 'libdiorite0.2', '--server', 'tiliado.eu', '--protocol', 'https', '-u', 'kitt', '-t', '89c3f084767ae01faaacf1ad0318cf8291438f7a']
+ ['apt-get', 'remove', '-y', 'libdiorite0.2*']
Reading package lists...
Building dependency tree...
Reading state information...
Package 'libdiorite0.2-dbg' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  gir1.2-rb-3.0 gir1.2-secret-1 glib-networking:i386
  gstreamer1.0-plugins-base:i386 guile-2.0-libs kde-l10n-engb
  kde-telepathy-approver kde-telepathy-auth-handler kde-telepathy-contact-list
  kde-telepathy-desktop-applets kde-telepathy-filetransfer-handler
  kde-telepathy-integration-module kde-telepathy-text-ui libabw-0.1-1v5
  libatk-bridge2.0-0:i386 libatk1.0-0:i386 libatspi2.0-0:i386
  libavahi-gobject0 libboost-filesystem1.58.0:i386 libboost-system1.58.0:i386
  libc-ares2 libcairo-gobject2:i386 libcairo2:i386 libcdparanoia0:i386
  libcdr-0.1-1 libcmis-0.5-5v5 libcolord2:i386 libcurl3:i386 libdatrie1:i386
  libdbus-glib-1-2:i386 libdbusmenu-glib4:i386 libdbusmenu-gtk3-4:i386
  libdbusmenu-gtk4:i386 libdmapsharing-3.0-2 libe-book-0.1-1 libegl1-mesa:i386
  libeot0 libepoxy0:i386 libetonyek-0.1-1 libevdev2:i386 libfreehand-0.1-1
  libgbm1:i386 libgc1c2 libgdk-pixbuf2.0-0:i386 libglib2.0-0:i386
  libgraphite2-3:i386 libgsm1:i386 libgstreamer-plugins-base1.0-0:i386
  libgstreamer1.0-0:i386 libgtk-3-0:i386 libgtk2.0-0:i386 libgudev-1.0-0:i386
  libguess1 libharfbuzz0b:i386 libinput10:i386 libjson-glib-1.0-0:i386
  libkf5emoticons-bin libkf5emoticons-data libkf5emoticons5 libkf5parts-data
  libkf5parts-plugins libkf5parts5 libkf5webkit5 libktpotr9 libmcrypt4:i386
  libmirclient9:i386 libmircommon5:i386 libmirprotobuf3:i386 libmspub-0.1-1
  libmtdev1:i386 libmwaw-0.3-3 libodbc1:i386 libodfgen-0.1-1 libopus0:i386
  liborc-0.4-0:i386 liborcus-0.10-0v5 libotr5 libpagemaker-0.0-0
  libpango-1.0-0:i386 libpangocairo-1.0-0:i386 libpangoft2-1.0-0:i386
  libpcap0.8:i386 libpcre16-3:i386 libpixman-1-0:i386 libprotobuf-lite9v5:i386
  libproxy1v5:i386 libqca-qt5-2 libqca-qt5-2-plugins libqt5concurrent5
  libqt5core5a:i386 libqt5dbus5:i386 libqt5declarative5:i386 libqt5gui5:i386
  libqt5network5:i386 libqt5script5:i386 libqt5sql5:i386
  libqt5sql5-sqlite:i386 libqt5svg5:i386 libqt5widgets5:i386
  libqt5x11extras5:i386 libqt5xmlpatterns5:i386 libreoffice-gtk
  librest-0.7-0:i386 librevenge-0.0-0 librhythmbox-core9 librtmp1:i386
  librubberband2v5 libsdl2-2.0-0 libsndio6.1 libsoup-gnome2.4-1:i386
  libsoup2.4-1:i386 libthai0:i386 libtheora0:i386 libva-wayland1 libva-x11-1
  libvisio-0.1-1 libvisual-0.4-0:i386 libwacom2:i386 libwayland-client0:i386
  libwayland-cursor0:i386 libwayland-egl1-mesa:i386 libwayland-server0:i386
  libwpd-0.10-10 libwpg-0.3-3 libwps-0.4-4 libxcb-icccm4:i386
  libxcb-image0:i386 libxcb-keysyms1:i386 libxcb-randr0:i386
  libxcb-render-util0:i386 libxcb-render0:i386 libxcb-shape0:i386
  libxcb-shm0:i386 libxcb-util1:i386 libxcb-xfixes0:i386 libxcb-xkb1:i386
  libxkbcommon-x11-0:i386 libxkbcommon0:i386 nuvolaplayer3-8tracks
  nuvolaplayer3-all-services nuvolaplayer3-amazon-cloud-player
  nuvolaplayer3-bandcamp nuvolaplayer3-deezer nuvolaplayer3-google-play-music
  nuvolaplayer3-groove nuvolaplayer3-jango nuvolaplayer3-kexp
  nuvolaplayer3-logitech-media-server nuvolaplayer3-mixcloud
  nuvolaplayer3-plex nuvolaplayer3-siriusxm nuvolaplayer3-soundcloud
  nuvolaplayer3-spotify nuvolaplayer3-tunein nuvolaplayer3-yandex-music
  nuvolaplayer3-youtube ofono python3-mako qml-module-org-kde-telepathy
  qml-module-qt-labs-folderlistmodel qml-module-qt-labs-settings
  qml-module-ubuntu-web rhythmbox-data telepathy-gabble telepathy-logger
  telepathy-ring telepathy-salut wine-devel wine-devel-amd64
  wine-devel-i386:i386
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  libdiorite0.2 nuvolaplayer3
0 upgraded, 0 newly installed, 2 to remove and 2 not upgraded.
6 not fully installed or removed.
After this operation, 2.095 kB disk space will be freed.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 380241 files and directories currently installed.)
Removing nuvolaplayer3 (3.0.4-0+1~xenial) ...
Removing libdiorite0.2 (0.2.1-0+1~xenial) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up pcscd (1.8.14-1ubuntu1) ...
insserv: warning: script 'K99pwrstatd' missing LSB tags and overrides
insserv: warning: script 'pwrstatd' missing LSB tags and overrides
insserv: There is a loop between service plymouth and procps if started
insserv:  loop involving service procps at depth 2
insserv:  loop involving service udev at depth 1
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Starting pwrstatd depends on plymouth and therefore on system facility `$all' which can not be true!
insserv: Max recursions depth 99 reached
insserv: There is a loop at service pwrstatd if started
insserv: There is a loop between service pwrstatd and hwclock if started
insserv:  loop involving service hwclock at depth 1
insserv: There is a loop at service plymouth if started
insserv:  loop involving service networking at depth 4
insserv: There is a loop between service plymouth and urandom if started
insserv:  loop involving service urandom at depth 4
insserv:  loop involving service mountdevsubfs at depth 2
insserv:  loop involving service pwrstatd at depth 1
insserv: There is a loop between service pwrstatd and dns-clean if started
insserv:  loop involving service dns-clean at depth 1
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package pcscd (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of opensc:
 opensc depends on pcscd; however:
  Package pcscd is not configured yet.

dpkg: error processing package opensc (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libdigidoc2:amd64:
 libdigidoc2:amd64 depends on opensc; however:
  Package opensc is not configured yet.
 libdigidoc2:amd64 depends on pcscd; however:
  Package pcscd is not configured yet.

dpkg: error processing package libdigidoc2:amd64 (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because the error message indicates its a followup error from a previous failure.
dpkg: dependency problems prevent configuration of libdigidocpp0:
 libdigidocpp0 depends on opensc; however:
  Package opensc is not configured yet.

dpkg: error processing package libdigidocpp0 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of qdigidoc:
 qdigidoc depends on libdigidoc2; however:
  Package libdigidoc2:amd64 is not configured yet.
 qdigidoc depends on libdigidocpp0; however:
  Package libdigidocpp0 is not configured yet.

dpkg: error processing package qdigidoc (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of nautilus-qdigidoc:
 nautilus-qdigidoc depends on qdigidoc; however:
  Package qdigidoc is not configured yet.

dpkg: error processing package nautilus-qdigidoc (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
No apport report written because MaxReports is reached already
No apport report written because MaxReports is reached already
Errors were encountered while processing:
 pcscd
 opensc
 libdigidoc2:amd64
 libdigidocpp0
 qdigidoc
 nautilus-qdigidoc
E: Sub-process /usr/bin/dpkg returned an error code (1)
Command '['apt-get', 'remove', '-y', 'libdiorite0.2*']' returned non-zero exit status 100
+ ['rm', '-fv', '/tmp/40554B8FA5FE6F6A.gpg']
+ ['wget', '-O', '/tmp/40554B8FA5FE6F6A.gpg', 'http://keyserver.ubuntu.com/pks/lookup?search=0x40554B8FA5FE6F6A&op=get']
--2016-11-12 10:37:38--  http://keyserver.ubuntu.com/pks/lookup?search=0x40554B8FA5FE6F6A&op=get
Resolving keyserver.ubuntu.com (keyserver.ubuntu.com)... 91.189.90.55, 91.189.89.49
Connecting to keyserver.ubuntu.com (keyserver.ubuntu.com)|91.189.90.55|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11454 (11K) [text/html]
Saving to: ‘/tmp/40554B8FA5FE6F6A.gpg’

     0K .......... .                                          100% 91,9M=0s

2016-11-12 10:37:38 (91,9 MB/s) - ‘/tmp/40554B8FA5FE6F6A.gpg’ saved [11454/11454]

+ ['apt-key', 'add', '/tmp/40554B8FA5FE6F6A.gpg']
OK
+ ['rm', '-fv', '/tmp/40554B8FA5FE6F6A.gpg']
removed '/tmp/40554B8FA5FE6F6A.gpg'
+ [disable repos: tiliado.eu => diorite]
+ [makedirs '/etc/apt/sources.list.d']
+ [arch 'x86_64']
+ [write '/etc/apt/sources.list.d/tiliado-diorite.list']
deb https://kitt:89c3f084767ae01faaacf1ad0318cf8291438f7a@tiliado.eu/diorite/repository/deb/ xenial stable # diorite (stable)

+ ['apt-get', 'update']
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

Warning: Database update command failed, probably because of broken repositories in your APT sources lists. Error code:
+ ['apt-get', 'install', '-y', 'libdiorite0.2']
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
Subprocess Error: Command '['apt-get', 'install', '-y', 'libdiorite0.2']' returned non-zero exit status 100
+ [Return code = 4]

**Comment by jiri-janousek** [comment]
Hello @illumine666. The installation failed because of incomplete installation of other packages. Could you try to run `sudo apt-get install -f` in order to fix that?
