### ISSUE TITLE
installing nuvoplayer & tiliado repositories failed

### ISSUE THREAD

**Issue by illumine666** [tiliado/tiliado-repositories#15]
Errors were encountered while processing:
 samba
 pcscd
 opensc
 libdigidoc2:amd64
 libdigidocpp0
 qdigidoc
 nautilus-qdigidoc
E: Sub-process /usr/bin/dpkg returned an error code (1)
Subprocess Error: Command '['apt-get', 'install', '-y', 'nuvolaplayer3', 'nuvolaplayer3-dbg']' returned non-zero exit status 100
+ [Return code = 4]

**Comment by jiri-janousek** [comment]
Hello @illumine666. Please don't create new installation bug reports until your issue #14 is resolved.
