### ISSUE TITLE
hey, got the error below

### ISSUE THREAD

**Issue by veldrin23** [tiliado/tiliado-repositories#17]
+ ['/usr/bin/tiliado-repositories', '-d', 'ubuntu', '-r', 'xenial', '-v', 'stable', '-p', 'nuvolaplayer', '-i', 'nuvolaplayer3', '--server', 'tiliado.eu', '--protocol', 'https', '-u', 'veldrin23', '-t', '4f74d18a7357008a3c7d3ca60ea5509d6e159142']
+ ['apt-get', 'remove', '-y', 'nuvolaplayer3*']
Reading package lists...
Building dependency tree...
Reading state information...
Package 'nuvolaplayer' is not installed, so not removed
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 linux-headers-4.4.25-040425-generic : Depends: linux-headers-4.4.25-040425 but it is not installable
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
Command '['apt-get', 'remove', '-y', 'nuvolaplayer3*']' returned non-zero exit status 100
+ ['rm', '-fv', '/tmp/40554B8FA5FE6F6A.gpg']
+ ['wget', '-O', '/tmp/40554B8FA5FE6F6A.gpg', 'http://keyserver.ubuntu.com/pks/lookup?search=0x40554B8FA5FE6F6A&op=get']
--2016-12-15 14:14:42--  http://keyserver.ubuntu.com/pks/lookup?search=0x40554B8FA5FE6F6A&op=get
Resolving keyserver.ubuntu.com (keyserver.ubuntu.com)... 91.189.90.55, 91.189.89.49
Connecting to keyserver.ubuntu.com (keyserver.ubuntu.com)|91.189.90.55|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11454 (11K) [text/html]
Saving to: ‘/tmp/40554B8FA5FE6F6A.gpg’

     0K .......... .                                          100% 27.8M=0s

2016-12-15 14:14:43 (27.8 MB/s) - ‘/tmp/40554B8FA5FE6F6A.gpg’ saved [11454/11454]

+ ['apt-key', 'add', '/tmp/40554B8FA5FE6F6A.gpg']
OK
+ ['rm', '-fv', '/tmp/40554B8FA5FE6F6A.gpg']
removed '/tmp/40554B8FA5FE6F6A.gpg'
+ [disable repos: tiliado.eu => nuvolaplayer]
+ [makedirs '/etc/apt/sources.list.d']
+ [arch 'x86_64']
+ [write '/etc/apt/sources.list.d/tiliado-nuvolaplayer.list']
deb https://veldrin23:4f74d18a7357008a3c7d3ca60ea5509d6e159142@tiliado.eu/nuvolaplayer/repository/deb/ xenial stable # nuvolaplayer (stable)

+ ['apt-get', 'update']
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://za.archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://za.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:5 http://ppa.launchpad.net/costales/folder-color/ubuntu xenial InRelease
Hit:6 http://dl.google.com/linux/chrome/deb stable Release
Ign:7 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial InRelease
Get:8 http://za.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Hit:10 http://ppa.launchpad.net/mystic-mirage/pycharm/ubuntu xenial InRelease
Get:11 http://za.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [440 kB]
Ign:12 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial Release
Ign:13 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main amd64 Packages
Get:14 http://security.ubuntu.com/ubuntu xenial-security/main amd64 DEP-11 Metadata [68.2 kB]
Get:15 https://tiliado.eu/nuvolaplayer/repository/deb xenial InRelease [15.2 kB]
Ign:16 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main i386 Packages
Get:17 http://za.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [433 kB]
Ign:18 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main all Packages
Get:19 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable amd64 Packages [4252 B]
Ign:20 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main Translation-en
Get:21 https://tiliado.eu/nuvolaplayer/repository/deb xenial/stable i386 Packages [4260 B]
Get:22 http://za.archive.ubuntu.com/ubuntu xenial-updates/main amd64 DEP-11 Metadata [303 kB]
Ign:23 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main amd64 DEP-11 Metadata
Get:24 http://security.ubuntu.com/ubuntu xenial-security/main DEP-11 64x64 Icons [48.0 kB]
Ign:25 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main DEP-11 64x64 Icons
Get:26 http://za.archive.ubuntu.com/ubuntu xenial-updates/main DEP-11 64x64 Icons [188 kB]
Ign:13 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main amd64 Packages
Get:27 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 DEP-11 Metadata [19.4 kB]
Ign:16 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main i386 Packages
Get:28 http://za.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [370 kB]
Get:29 http://security.ubuntu.com/ubuntu xenial-security/universe DEP-11 64x64 Icons [25.6 kB]
Ign:18 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main all Packages
Get:30 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 DEP-11 Metadata [212 B]
Ign:20 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main Translation-en
Get:31 http://za.archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [366 kB]
Ign:23 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:25 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main DEP-11 64x64 Icons
Get:32 http://za.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 DEP-11 Metadata [121 kB]
Ign:13 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main amd64 Packages
Get:33 http://za.archive.ubuntu.com/ubuntu xenial-updates/universe DEP-11 64x64 Icons [145 kB]
Ign:16 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main i386 Packages
Get:34 http://za.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 DEP-11 Metadata [2520 B]
Get:35 http://za.archive.ubuntu.com/ubuntu xenial-backports/main amd64 DEP-11 Metadata [208 B]
Get:36 http://za.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 DEP-11 Metadata [212 B]
Get:37 http://za.archive.ubuntu.com/ubuntu xenial-backports/multiverse amd64 DEP-11 Metadata [212 B]
Ign:18 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main all Packages
Ign:20 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main Translation-en
Ign:23 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:25 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main DEP-11 64x64 Icons
Ign:13 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main amd64 Packages
Hit:38 http://repo.steampowered.com/steam precise InRelease
Ign:16 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main i386 Packages
Ign:18 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main all Packages
Ign:20 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main Translation-en
Ign:23 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:25 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main DEP-11 64x64 Icons
Ign:13 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main amd64 Packages
Ign:16 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main i386 Packages
Ign:18 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main all Packages
Ign:20 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main Translation-en
Ign:23 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:25 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main DEP-11 64x64 Icons
Err:13 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:16 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main i386 Packages
Ign:18 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main all Packages
Ign:20 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main Translation-en
Ign:23 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:25 http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial/main DEP-11 64x64 Icons
AppStream cache update completed, but some metadata was ignored due to errors.
Fetched 2861 kB in 8s (331 kB/s)
Reading package lists...
W: The repository 'http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/kroq-gar78/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

Warning: Database update command failed, probably because of broken repositories in your APT sources lists. Error code:
+ ['apt-get', 'install', '-y', 'nuvolaplayer3']
Reading package lists...
Building dependency tree...
Reading state information...
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 linux-headers-4.4.25-040425-generic : Depends: linux-headers-4.4.25-040425 but it is not installable
 nuvolaplayer3 : Depends: nuvolaplayer3-all-services but it is not going to be installed
                 Depends: libdiorite0.2 (>= 0.2.0) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
Subprocess Error: Command '['apt-get', 'install', '-y', 'nuvolaplayer3']' returned non-zero exit status 100
+ [Return code = 4]

**Comment by jiri-janousek** [comment]
Hello @veldrin23. Thanks for taking the time to report your issue. The installation has failed because there are dependency problems on your system. They must be resolved first.

> The following packages have unmet dependencies:
linux-headers-4.4.25-040425-generic : Depends: linux-headers-4.4.25-040425 but it is not installable
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

As the error message suggests, you can try running `apt-get -f install` as root/superuser/sudo to fix the issue. Let me know whether it helps.

**Comment by jiri-janousek** [comment]
Closing bugs without response from the reporter.
