### ISSUE TITLE
Failed install Fedora 25

### ISSUE THREAD

**Issue by aia832003** [tiliado/tiliado-repositories#19]
Total                                           200 kB/s | 1.7 MB     00:08     
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Package nuvolaplayer3-8tracks-5.1-2.fc25.x86_64.rpm is not signed
Subprocess Error: Command '['dnf', 'install', '-y', 'nuvolaplayer3']' returned non-zero exit status 1
+ [Return code = 4]

**Comment by jiri-janousek** [comment]
Hello @aia832003. Thanks for taking the time to report this issue. I've re-signed the packages. I'm keeping this ticket open to remind me that I have to look into my build scripts in order to fix the cause of the issue.
