### ISSUE TITLE
Provide repositories for openSUSE

### ISSUE THREAD

**Issue by lbssousa** [tiliado/tiliado-repositories#2]
Do you have plans to provide Tiliado Repositories for openSUSE? I'm not sure if current Fedora repo works fine for openSUSE, but anyway a dedicated repo for openSUSE would bu great! I suggest supporting the following codenames:
- 13.2 (current stable release)
- Leap 42.1 (next stable release, scheduled for November 4th)
- Tumbleweed (rolling release)

**Comment by jiri-janousek** [comment]
Hello @lbssousa. I don't plan to provide packages for openSUSE in the near future as there is hardly enough funded time to maintain packages for Fedora. However, if you are seriously interested, you can hire me to make them :-)

**Comment by jiri-janousek** [comment]
Closing as there are not enough funds for that.

**Comment by jiri-janousek** [comment]
Flatpak is the future: #13
