### ISSUE TITLE
DNS Failure with DNSMasq

### ISSUE THREAD

**Issue by MetricMike** [tiliado/tiliado-repositories#21]
Running the Spotify app gives me `Error resolving 'play.spotify.com': Temporary failure in name resolution` and a dialog error titled "Integration error" with `Failed to inject JavaScript API. Function 'Nuvola.core.emit' failed. file:///app/share/nuvolaplayer3/web_apps/spotify/integrate.js:99: SecurityError: The operation is insecure. The application might not function properly.`

The two changes I made which I think led to this were installing dnsmasq (directs *.dev to 127.0.0.1) and disabling DNSStubListener on systemd-resovlerd. I believe this has the consequence of forcing DNS lookups through DNSMasq, but I'm not 100%.

Using the official Spotify client or the web player through Chrome work fine. 

Any ideas? 

---

`flatpak list`
```
eu.tiliado.Nuvola/x86_64/stable           system,current
eu.tiliado.NuvolaAppSpotify/x86_64/stable system,current
org.gnome.Platform.Locale/x86_64/3.22     system,runtime
org.gnome.Platform/x86_64/3.22            system,runtime
```
`flatpak info eu.tiliado.NuvolaAppSpotify`
```
app/eu.tiliado.NuvolaAppSpotify/x86_64/stable nuvola c91cf23a8d3beffdf30f43fb333c7b6c7f20ef234395ac8d1a7edb1154a5945c 223.0 MB
```
`lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
```
`uname -r`
```
4.10.0-20-generic
```

**Comment by jiri-janousek** [comment]
Issue moved to [tiliado/nuvolaplayer #329](https://github.com/tiliado/nuvolaplayer/issues/329) via [**ZenHub**](https://www.zenhub.com/)
