### ISSUE TITLE
Amazon Cloud Player installation fails on fc24

### ISSUE THREAD

**Issue by whitedwarfsun** [tiliado/tiliado-repositories#22]
The installation of nuvolaplayer3-amazon-cloud-player fails on fc24. The repodata seems to be old: even after a `dnf clean all`, the repo lists `nuvolaplayer3-amazon-cloud-player-5.3-3.fc24.x86_64` to be the latest version. However, the [direct listing](https://tiliado.eu/nuvolaplayer/repository/rpm/fc24/x86_64/stable/packages/) shows only `nuvolaplayer3-amazon-cloud-player-5.4-1.fc24.x86_64`. Other packages are affected, too, e.g. nuvolaplayer3-core (repodata: `3.0.7-1.fc24`, listing: `3.0.8-1.fc24`).

**Comment by jiri-janousek** [comment]
Hello @whitedwarfsun. Thanks for taking the time to report this issue. It seems that my build script had a bug that was not triggered with Python 3.4 but Python 3.5 is less forgiving. I have uploaded new repodata. Could you check it works?

**Comment by whitedwarfsun** [comment]
Seems fine now. Thanks!
