### ISSUE TITLE
Expired APT Key

### ISSUE THREAD

**Issue by pizzadude** [tiliado/tiliado-repositories#23]
Hi, after running an apt update I noticed your apt key is expired.

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://tiliado.eu/nuvolaplayer/repository/deb zesty InRelease: The following signatures were invalid: EXPKEYSIG 40554B8FA5FE6F6A Jiří Janoušek <********.jiri@gmail.com>

**Comment by jiri-janousek** [comment]
Hello @pizzadude. Thanks for reporting this issue. I've returned from a vacation today so I'll look at it as soon as possible.

**Comment by jiri-janousek** [comment]
Actually, the key on the Ubuntu keyserver is valid until 2018-12-31. Could you try to run `sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 40554B8FA5FE6F6A` to update the key on your  system?

**Comment by pizzadude** [comment]
Thanks, that fixed it.

**Comment by jiri-janousek** [comment]
[Instructions added to a blog post](https://medium.com/nuvola-news/nuvola-3-0-9-688e20f18a1c), closing.
